Rails.application.config.middleware.use OmniAuth::Builder do
  TWITTER_CONSUMER_KEY    = ENV["TWITTER_CONSUMER_KEY"]
  TWITTER_CONSUMER_SECRET = ENV["TWITTER_CONSUMER_SECRET"]
  provider :twitter, TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET
end
